spring.application.name=fake-account-detection

spring.datasource.url=jdbc:postgresql://localhost:5432/fake_account_detection
spring.datasource.username=postgres
spring.datasource.password=Postgressql123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect